"""message

Revision ID: f7a9766f83bc
Revises: dc970f1ce4ab
Create Date: 2023-04-17 05:28:48.517527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a9766f83bc'
down_revision = 'dc970f1ce4ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
     # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ph_number', sa.VARCHAR(),nullable=True))


def downgrade() -> None:
   
    # ### end Alembic commands ###
     op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
